<a href="https://colab.research.google.com/github/vythao181226-netizen/HUB/blob/main/BTN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pdfplumber

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.9)
Requirement already satisfied: pdfminer.six==20251230 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.7.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.7)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)

In [ ]:
import pdfplumber
import pandas as pd
import requests
def collect_table_from_drive(url, page_num):
    try:
        file_id = url.split('/')[-2]
        direct_link = f'https://drive.google.com/uc?id={file_id}'
        local_path = "chude1.pdf"

        response = requests.get(direct_link)
        with open(local_path, 'wb') as f:
            f.write(response.content)

        with pdfplumber.open(local_path) as pdf:
            page = pdf.pages[page_num - 1]
            table = page.extract_table()

            if table:
                df = pd.DataFrame(table[1:], columns=table[0])
                print(f"--- Đã thu thập dữ liệu trang {page_num} thành công! ---")
                return df
        return None
    except Exception as e:
        print(f"Lỗi quy trình 1-2: {e}")
        return None
drive_url = 'https://drive.google.com/file/d/1ryF9_RvO8yL7MFIt7F66qYsMBWY0kxeB/view?usp=sharing'

In [ ]:
df_khung_nghien_cuu = collect_table_from_drive(drive_url, page_num=4)
if df_khung_nghien_cuu is not None:
    df_khung_nghien_cuu = df_khung_nghien_cuu.replace('\n', ' ', regex=True)
    print("\n--- BẢNG 1: KHUNG NGHIÊN CỨU ---")
    display(df_khung_nghien_cuu)
else:
    print("Không tìm thấy dữ liệu để hiển thị.")

--- Đã thu thập dữ liệu trang 4 thành công! ---

--- BẢNG 1: KHUNG NGHIÊN CỨU ---

,Nhân tố ảnh hưởng,Biến đo lường,Giải thiết mối\ntương quan
0,Quy mô doanh nghiệp,Tổng tài sản,+/-
1,Khả năng sinh lời,"ROA, ROE, ROS",+/-
2,Tỷ số nợ,Nợ/ Tổng tài sản,+/-
3,Cấu trúc tài sản,Tài sản lưu động/ Tổng tài sản,+/-
4,Tỷ lệ vốn lưu động,(Tài sản ngắn hạn - Nợ ngắn hạn)/ Tổng tài sản,+/-
5,GDP,Tăng trưởng GDP,+/-

In [ ]:
def extract_complete_model_details(path):
    try:
        import pdfplumber
        with pdfplumber.open(path) as pdf:
            full_combined_text = ""
            for i in [3, 4]:
                full_combined_text += pdf.pages[i].extract_text() + "\n"

            print("--- MÔ HÌNH NGHIÊN CỨU ---")
            print("Phương trình: Y1 = α0 + α1X1 + α2X2 + α3X3 + α4X4 + α5X5 + α6X6 + α7X7 + α8X8 + Ei")
            print("\nTrong đó:")

            lines = full_combined_text.split('\n')

            target_codes = ["Y1:", "X1:", "X2:", "X3:", "X4:", "X5:", "X6:", "X7:", "X8:", "Ei:"]

            history = set()

            for line in lines:
                for code in target_codes:
                    if code in line:
                        start_pos = line.find(code)
                        content = line[start_pos:].strip()

                        if content not in history:
                            print(content)
                            history.add(content)
                        break

    except Exception as e:
        print(f"Lỗi khi trích xuất: {e}")
extract_complete_model_details("chude1.pdf")

--- MÔ HÌNH NGHIÊN CỨU ---
Phương trình: Y1 = α0 + α1X1 + α2X2 + α3X3 + α4X4 + α5X5 + α6X6 + α7X7 + α8X8 + Ei

Trong đó:
Y1: Khả năng thanh toán ngắn hạn (CR)
X1: Quy mô doanh nghiệp (SIZE)
X2: Khả năng sinh lời của tài sản (ROA)
X3: Khả năng sinh lời của doanh thu thuần (ROS)
X4: Khả năng sinh lời của VCSH (ROE)
X5: Tỷ số nợ (DR)
X6: Cấu trúc tài sản (AS)
X7: Tỷ lệ vốn lưu động (WCR)
X8: GDP mô hình đa công tuyến ta sẽ tiến hành kiểm định Collinearity
Ei: các sai số ngẫu nhiên Statistics và đánh giá thông qua độ chấp nhận (Tolerance)

In [ ]:
import pdfplumber
import pandas as pd
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

def extract_pearson_table(path):
    try:
        with pdfplumber.open(path) as pdf:
            page = pdf.pages[4]

            table = page.extract_table(table_settings={
                "vertical_strategy": "lines",
                "horizontal_strategy": "lines",
            })

            if not table:
                print("Không tìm thấy bảng.")
                return

            df = pd.DataFrame(table)

            df.columns = df.iloc[0]
            df = df.drop(0)
            df = df.map(lambda x: str(x).replace('\n', ' ') if x else "")
            df.columns.values[0] = "Variable"
            df.columns.values[1] = "Measure"

            print("\n--- BẢNG 2: THỐNG KÊ MÔ TẢ MẪU NGHIÊN CỨU ---")
            print(df.to_markdown(index=False))

    except Exception as e:
        print(f"Lỗi: {e}")

extract_pearson_table("chude1.pdf")

--- BẢNG 2: THỐNG KÊ MÔ TẢ MẪU NGHIÊN CỨU ---
| Variable       | Measure   | CR      | SIZE           | ROA      | ROS      | ROE      | DR      | AS      | WCR     | GDP     |
|:---------------|:----------|:--------|:---------------|:---------|:---------|:---------|:--------|:--------|:--------|:--------|
|                | Valid     | 400     | 400            | 400      | 400      | 400      | 400     | 400     | 400     | 400     |
| N              |           |         |                |          |          |          |         |         |         |         |
|                | Missing   | 0       | 0              | 0        | 0        | 0        | 0       | 0       | 0       | 0       |
|                |           |         |                |          |          |          |         |         |         |         |
| Mean           |           | 3,27357 | 19158135411704 | 0,03711  | 1,06368  | -0,04020 | 0,51352 | 0,61769 | 0,26502 | 5,52200 |
| Std. Deviation |           | 7,26077 | 78376088172104 | 0,058418 | 19,5690  | 2,74440  | 0,20617 | 0,23984 | 0,26596 | 2,30023 |
| Minimum        |           | 0,067   | 18149208715    | -0,310   | -103,218 | -54,710  | 0,050   | 0,020   | -0,740  | 2,580   |
| Maximum        |           | 113,453 | 8493499590000  | 0,300    | 338,000  | 0,910    | 1,351   | 0,999   | 0,892   | 8,020   |

In [ ]:
def extract_vif_data_correctly(path):
    try:
        import pdfplumber
        import re

        with pdfplumber.open(path) as pdf:
            page = pdf.pages[5]
            text = page.extract_text()

            print("--- BẢNG 3: KIỂM ĐỊNH ĐA CỘNG TUYẾN ---")
            print(f"{'Biến':<10} | {'Tolerance':<15} | {'VIF':<10}")
            print("-" * 40)

            lines = text.split('\n')
            target_vars = ["SIZE", "ROA", "ROS", "ROE", "DR", "AS", "WCR", "GDP"]

            for line in lines:
                for var in target_vars:
                    if var in line:
                        numbers = re.findall(r'\d+[\.,]\d+', line)

                        if len(numbers) >= 2:
                            tolerance = numbers[-2]
                            vif = numbers[-1]
                            print(f"{var:<10} | {tolerance:<15} | {vif:<10}")
                        break

    except Exception as e:
        print(f"Lỗi khi trích xuất số liệu: {e}")

extract_vif_data_correctly("chude1.pdf")

--- BẢNG 3: KIỂM ĐỊNH ĐA CỘNG TUYẾN ---
Biến       | Tolerance       | VIF
----------------------------------------
AS         | 1,953           | 0,052
SIZE       | 0,975           | 1,026
ROA        | 0,856           | 1,168
ROS        | 0,839           | 1,192
ROE        | 0,955           | 1,047
DR         | 0,634           | 1,576
AS         | 0,474           | 2,110
WCR        | 0,414           | 2,414
GDP        | 0,935           | 1,069
ROA        | 2,913           | 8,683
ROS        | 6,200           | 12,996

In [ ]:
def extract_autocorrelation_table(path):
    try:
        import pdfplumber
        import re

        with pdfplumber.open(path) as pdf:
            if len(pdf.pages) <= 4:
                print("PDF không đủ trang.")
                return

            page = pdf.pages[4]
            text = page.extract_text()

            if not text:
                print("Không đọc được nội dung trang.")
                return

            print("--- BẢNG 4: KẾT QUẢ KIỂM ĐỊNH TỰ TƯƠNG QUAN ---")
            print(f"{'Model':<8} | {'R':<10} | {'R Square':<10} | {'Adj R2':<10} | {'Std Error':<12} | {'Durbin-Watson':<15}")
            print("-" * 80)

            lines = text.split('\n')

            for line in lines:
                if re.search(r'\b1\b', line):

                    numbers = re.findall(r'\d+[\.,]\d+', line)

                    if len(numbers) >= 5:
                        r = numbers[0]
                        r_square = numbers[1]
                        adj_r2 = numbers[2]
                        std_error = numbers[3]
                        dw = numbers[4]

                        print(f"{'1':<8} | {r:<10} | {r_square:<10} | {adj_r2:<10} | {std_error:<12} | {dw:<15}")
                        break

    except Exception as e:
        print(f"Lỗi khi trích xuất: {e}")

extract_autocorrelation_table("chude1.pdf")

--- BẢNG 4: KẾT QUẢ KIỂM ĐỊNH TỰ TƯƠNG QUAN ---
Model    | R          | R Square   | Adj R2     | Std Error    | Durbin-Watson
--------------------------------------------------------------------------------
1        | 0,441      | 0,195      | 0,178      | 6,581334     | 1,986

In [ ]:
import pdfplumber
import pandas as pd
def extract_correct_pearson_table(path, page_index):
    try:
        with pdfplumber.open(path) as pdf:
            page = pdf.pages[page_index]

            tables = page.extract_tables({
                "vertical_strategy": "lines",
                "horizontal_strategy": "lines"
            })

            if not tables:
                print("Không tìm thấy bảng.")
                return None
            target_table = None
            for t in tables:
                text = str(t).lower()
                if "pearson" in text or "sig. (2-tailed)" in text:
                    target_table = t
                    break

            if not target_table:
                target_table = tables[-1]
            raw_df = pd.DataFrame(target_table)

            raw_df = raw_df.applymap(
                lambda x: str(x).replace('\n', ' ').strip() if x else ""
            )

            headers = raw_df.iloc[0].tolist()
            df = raw_df[1:].reset_index(drop=True)

            headers = [
                h if h != "" else f"col_{i}"
                for i, h in enumerate(headers)
            ]

            df.columns = headers
            df.rename(columns={
                df.columns[0]: "Variable",
                df.columns[1]: "Measure"
            }, inplace=True)

            def find_previous_var(idx):
                for j in range(idx, -1, -1):
                    v = str(df.iloc[j]["Variable"]).strip()
                    if v != "":
                        return v
                return None

            clean_rows = []
            i = 0

            while i < len(df):
                row = df.iloc[i]

                var = str(row["Variable"]).strip()
                measure = str(row["Measure"]).strip().lower()

                if "pearson" in measure:

                    current_var = var if var != "" else find_previous_var(i)

                    data = row[2:].tolist()

                    if i + 1 < len(df):
                        next_row = df.iloc[i + 1]
                        next_measure = str(next_row["Measure"]).lower()

                        if "correlation" in next_measure or all(x == "" for x in data):
                            data = next_row[2:].tolist()
                            i += 1

                    clean_rows.append([current_var, "Pearson Correlation"] + data)

                elif "sig" in measure:
                    current_var = var if var != "" else find_previous_var(i)
                    clean_rows.append([current_var, "Sig. (2-tailed)"] + row[2:].tolist())

                elif measure == "n":
                    current_var = var if var != "" else find_previous_var(i)
                    clean_rows.append([current_var, "N"] + row[2:].tolist())

                i += 1

            final_df = pd.DataFrame(clean_rows, columns=df.columns)

            def convert_num(x):
                try:
                    return float(
                        str(x).replace(',', '.').replace('*', '')
                    )
                except:
                    return x

            final_df = final_df.applymap(convert_num)
            final_df["Variable"] = final_df["Variable"].replace([None, "", "None"], "CR")

            print("\n--- BẢNG 5: PHÂN TÍCH TƯƠNG QUAN PEARSON ---")
            print(final_df.to_markdown(index=False))
            final_df["Variable"] = final_df["Variable"].replace([None, "", "None"], "CR")
            return final_df

    except Exception as e:
        print(f"Lỗi: {e}")

extract_correct_pearson_table("chude1.pdf", 5)

--- BẢNG 5: PHÂN TÍCH TƯƠNG QUAN PEARSON ---
| Variable   | Measure             |   col_2 |   col_3 |   col_4 |   col_5 |   col_6 |    col_7 |   col_8 |   col_9 |
|:-----------|:--------------------|--------:|--------:|--------:|--------:|--------:|---------:|--------:|--------:|
| CR         | Pearson Correlation |  -0.028 |  -0.041 |   0.032 |   0.013 |  -0.166 |   0.079  |    0.35 |   0.104 |
| CR         | Sig. (2-tailed)     |   0.578 |   0.418 |   0     |   0.796 |   0.001 |   0.0113 |    0    |   0.037 |
| CR         | N                   | 400     | 400     | 400     | 400     | 400     | 400      |  400    | 400     |

,Variable,Measure,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9
0,CR,Pearson Correlation,-0.028,-0.041,0.032,0.013,-0.166,0.0790,0.35,0.104
1,CR,Sig. (2-tailed),0.578,0.418,0.000,0.796,0.001,0.0113,0.00,0.037
2,CR,N,400.000,400.000,400.000,400.000,400.000,400.0000,400.00,400.000

In [ ]:
def extract_table_6(path):
    import pdfplumber
    import re
    try:
        with pdfplumber.open(path) as pdf:

            if len(pdf.pages) < 5:
                print("PDF không đủ trang.")
                return

            page = pdf.pages[5] if len(pdf.pages) > 5 else pdf.pages[4]
            text = page.extract_text()

            if not text:
                print("Không đọc được nội dung.")
                return

            print("\n--- BẢNG 6: KIỂM ĐỊNH SỰ PHÙ HỢP CỦA MÔ HÌNH ---")
            print(f"{'Model':<6} | {'R':<6} | {'R2':<6} | {'AdjR2':<8} | {'StdErr':<10} | {'R2 Change':<10} | {'F':<6} | {'df1':<5} | {'df2':<5} | {'Sig':<6}")
            print("-" * 100)

            lines = text.split("\n")

            for line in lines:
                if re.search(r'\b1\b', line):

                    numbers = re.findall(r'\d+[\.,]\d+|\d+', line)

                    if len(numbers) >= 10:
                        model = "1"
                        r = numbers[1]
                        r2 = numbers[2]
                        adj_r2 = numbers[3]
                        stderr = numbers[4]
                        r2_change = numbers[5]
                        f_change = numbers[6]
                        df1 = numbers[7]
                        df2 = numbers[8]
                        sig = numbers[9]

                        print(f"{model:<6} | {r:<6} | {r2:<6} | {adj_r2:<8} | {stderr:<10} | {r2_change:<10} | {f_change:<6} | {df1:<5} | {df2:<5} | {sig:<6}")
                        return

            print("Không tìm thấy dữ liệu bảng 6.")
    except Exception as e:
        print("Lỗi:", e)

extract_table_6("chude1.pdf")

--- BẢNG 6: KIỂM ĐỊNH SỰ PHÙ HỢP CỦA MÔ HÌNH ---
Model  | R      | R2     | AdjR2    | StdErr     | R2 Change  | F      | df1   | df2   | Sig
----------------------------------------------------------------------------------------------------
1      | 0,441  | 0,195  | 0,178    | 6,581334   | 0,166      | 9,739  | 8     | 391   | 0,000

In [ ]:
import pdfplumber
import pandas as pd
def extract_model_summary(path, page_index=5):
    try:
        with pdfplumber.open(path) as pdf:
            page = pdf.pages[5]

            table = page.extract_table({
                "vertical_strategy": "lines",
                "horizontal_strategy": "lines"
            })

            if not table:
                print(f"Không tìm thấy bảng ở trang {page_index}.")
                return None

            df = pd.DataFrame(table)
            header_top = df.iloc[0].fillna("").tolist()
            header_bottom = df.iloc[1].fillna("").tolist()

            final_headers = []
            current_top = ""

            for top, bottom in zip(header_top, header_bottom):
                top = top.replace('\n', ' ').strip()
                bottom = bottom.replace('\n', ' ').strip()

                if top != "":
                    current_top = top

                if current_top and bottom and current_top != bottom:
                    final_headers.append(f"{current_top}_{bottom}")
                else:
                    final_headers.append(bottom if bottom else top)

            df.columns = final_headers
            df = df.drop([0, 1]).reset_index(drop=True)

            df = df[df.iloc[:, 0] != "a. Predictors: (Constant), GDP, AS, ROE, ROS, SIZE, ROA, DR, WCR"]

            df = df.map(lambda x: str(x).replace('\n', ' ').strip() if x else "")

            print("\n--- BẢNG 7: KIỂM ĐỊNH SỰ PHÙ HỢP CỦA MÔ HÌNH ---")
            print(df.to_markdown(index=False))

            return df

    except Exception as e:
        print(f"Lỗi: {e}")

extract_model_summary("chude1.pdf", page_index=5)

--- BẢNG 7: KIỂM ĐỊNH SỰ PHÙ HỢP CỦA MÔ HÌNH ---
| Model   |            | Unstandardized_Coefficients   |            | Standardized_Coefficients   | Standardized_t   | Standardized_Sig.   | Collinearity_Statistics   |       |
|:--------|:-----------|:------------------------------|:-----------|:----------------------------|:-----------------|:--------------------|:--------------------------|:------|
|         |            | B                             | Std. Error | Beta                        |                  |                     | Tolerance                 | VIF   |
|         | (Constant) | 2,913                         | 1,492      |                             | 1,953            | 0,052               |                           |       |
|         | SIZE       | -6,533                        | 0,000      | -0,071                      | -1,534           | 0,126               | 0,975                     | 1,026 |
|         | ROA        | 8,683                         | 1,094      | -0,150                      | -3,066           | 0,002               | 0,856                     | 1,168 |
|         | ROS        | 2,428                         | 0,647      | 0,186                       | 3,753            | 0,000               | 0,839                     | 1,192 |
|         | ROE        | 0,039                         | 0,123      | 0,015                       | 0,321            | 0,749               | 0,955                     | 1,047 |
|         | DR         | -1,384                        | 2,006      | 0,039                       | 0,690            | 0,491               | 0,634                     | 1,576 |
|         | AS         | 6,200                         | 1,995      | -0,205                      | -3,107           | 0,002               | 0,474                     | 2,110 |
|         | WCR        | 12,996                        | 1,925      | 0,476                       | 6,752            | 0,000               | 0,414                     | 2,414 |
|         | GDP        | 0,072                         | 0,148      | 0,023                       | 0,485            | 0,628               | 0,935                     | 1,069 |

,Model,,Unstandardized_Coefficients,,Standardized_Coefficients,Standardized_t,Standardized_Sig.,Collinearity_Statistics,
0,,,B,Std. Error,Beta,,,Tolerance,VIF
1,,(Constant),"2,913","1,492",,"1,953","0,052",,
2,,SIZE,"-6,533","0,000","-0,071","-1,534","0,126","0,975","1,026"
3,,ROA,"8,683","1,094","-0,150","-3,066","0,002","0,856","1,168"
4,,ROS,"2,428","0,647","0,186","3,753","0,000","0,839","1,192"
5,,ROE,"0,039","0,123","0,015","0,321","0,749","0,955","1,047"
6,,DR,"-1,384","2,006","0,039","0,690","0,491","0,634","1,576"
7,,AS,"6,200","1,995","-0,205","-3,107","0,002","0,474","2,110"
8,,WCR,"12,996","1,925","0,476","6,752","0,000","0,414","2,414"
9,,GDP,"0,072","0,148","0,023","0,485","0,628","0,935","1,069"